### ISSUE TITLE
how i can change email in bot?

### ISSUE THREAD

**Issue by GlagolevEvgenii** [f213/selfmailbot#157]
. I need to change email where it sends the messages. Tried "Stop and block bot" button, it asks to enter email after /start command but if I enter new one, it sends it to old email, so the bot is still attached to old email. Tried various commands like /restart but didn't helped.I need to change my regular email to things

Thanks in advance.

**Comment by NorseUA** [comment]
@GlagolevEvgenii You were so close) Just use command "/reset"

**Comment by GlagolevEvgenii** [comment]
> @GlagolevEvgenii You were so close) Just use command "/reset"

ЁПТ
