### ISSUE TITLE
Проблема с отправкой сообщений которые содержат картинки.

### ISSUE THREAD

**Issue by teamkiller7112** [f213/selfmailbot#3]
**Ситуация:** Есть сообщение, которое содержит текст и картинку, которое пересылаем боту.
**Текущий результат:** на почту приходит только картинка.
Было бы круто, если бот присылал и картинку, и текст.

Пример сообщения:
![image](https://user-images.githubusercontent.com/9117949/58986683-9eebeb80-87e6-11e9-90ab-346e5fa363f2.png)

Письмо:
![image](https://user-images.githubusercontent.com/9117949/58986695-a7dcbd00-87e6-11e9-9e5c-c134fa912212.png)

**Comment by kuntashov** [comment]
> Было бы круто, если бот присылал и картинку, и текст.

Сделал в https://github.com/f213/selfmailbot/pull/7

Можно потестировать на боте @MySelfMailBot (этот бот поднят только для тестов)

Пример результата (в продолжение примера топикстартера):

![Screenshot_20191013_011752](https://user-images.githubusercontent.com/1042299/66708058-ae161380-ed5b-11e9-8203-2d1a9bcc9c87.png)

**Comment by teamkiller7112** [comment]
@kuntashov 
Очень круто! Все работает как часы
