### ISSUE TITLE
Using another email

### ISSUE THREAD

**Issue by fash1k** [f213/selfmailbot#4]
Hello, I am newbie to Python but I found your bot pretty useful. I am using dockerized one. I need to change email where it sends the messages. Tried "Stop and block bot" button, it asks to enter email after /start command but if I enter new one, it sends it to old email, so the bot is still attached to old email. Tried various commands like /restart but didn't helped. Sorry if my question is dummy but could your give me a solution?:) Thanks in advance.

**Comment by f213** [comment]
Currently there is no option to reset the email. I think we should implement a command for that, like `/reset` — it should completely drop the user record from the db.

Feel free to make a PR for this :-)

**Comment by f213** [comment]
The command is implemented.

Just type `/reset` and the bot will ask you for the new email

**Comment by f213** [comment]
Unfortunately, reset command works only for non-confirmed users, e.g. when you did not received any email from the bot.

I think we should add another command to reset the email and re-confirm the user, so i will reopen this issue.

**Comment by f213** [comment]
@grepto This issue might be a challenge for you :-)

**Comment by grepto** [comment]
> I think we should add another command to reset the email and re-confirm the user, so i will reopen this issue.

What is the point of having two different commands to change the e-mail address depending on whether or not the user has received any messages? It's a modality.

I suggest we use one command to change the address.

**Comment by grepto** [comment]
I broke my head thinking why it should be challenge. Issue look simple. I guess we'll just have to add one more command handler for /reset. This handler should not have any filters. 

Something like this
```python
dispatcher.add_handler(CommandHandler('reset', reset_email))
```

Maybe there's some other reason why we can't reset email for users to whom bot has already sent mail?

**Comment by f213** [comment]
> Maybe there's some other reason why we can't reset email for users to whom bot has already sent mail?

We should reset user's confirmation status during email reset — otherwise there will be an ability to confirm an email, change it, and send emails to the new, unconfirmed, one.

**Comment by grepto** [comment]
> We should reset user's confirmation status during email reset

Agree. That's why [I made a reset confirmation status](https://github.com/f213/selfmailbot/blob/9fdcf0c4e834e0c9dd833f6967afdcf8522b9c35/src/app.py#L36) for user when he use `/reset`

**Comment by f213** [comment]
The `/reset` command is usable in production now. Thank you @grepto!
